// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/avc-dev/url-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

type MockGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerator) EXPECT() *MockGenerator_Expecter {
	return &MockGenerator_Expecter{mock: &_m.Mock}
}

// GenerateBatchCodes provides a mock function with given fields: count
func (_m *MockGenerator) GenerateBatchCodes(count int) []model.Code {
	ret := _m.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBatchCodes")
	}

	var r0 []model.Code
	if rf, ok := ret.Get(0).(func(int) []model.Code); ok {
		return rf(count)
	}
	if rf, ok := ret.Get(0).(func(int) model.Code); ok {
		r0 = []model.Code{rf(count)}
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Code)
		}
	}

	return r0
}

// MockGenerator_GenerateBatchCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBatchCodes'
type MockGenerator_GenerateBatchCodes_Call struct {
	*mock.Call
}

// GenerateBatchCodes is a helper method to define mock.On call
//   - count int
func (_e *MockGenerator_Expecter) GenerateBatchCodes(count interface{}) *MockGenerator_GenerateBatchCodes_Call {
	return &MockGenerator_GenerateBatchCodes_Call{Call: _e.mock.On("GenerateBatchCodes", count)}
}

func (_c *MockGenerator_GenerateBatchCodes_Call) Run(run func(count int)) *MockGenerator_GenerateBatchCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockGenerator_GenerateBatchCodes_Call) Return(_a0 []model.Code) *MockGenerator_GenerateBatchCodes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenerator_GenerateBatchCodes_Call) RunAndReturn(run func(int) []model.Code) *MockGenerator_GenerateBatchCodes_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCode provides a mock function with given fields:
func (_m *MockGenerator) GenerateCode() model.Code {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateCode")
	}

	var r0 model.Code
	if rf, ok := ret.Get(0).(func() model.Code); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.Code); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Code)
		}
	}

	return r0
}

// MockGenerator_GenerateCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCode'
type MockGenerator_GenerateCode_Call struct {
	*mock.Call
}

// GenerateCode is a helper method to define mock.On call
func (_e *MockGenerator_Expecter) GenerateCode() *MockGenerator_GenerateCode_Call {
	return &MockGenerator_GenerateCode_Call{Call: _e.mock.On("GenerateCode")}
}

func (_c *MockGenerator_GenerateCode_Call) Run(run func()) *MockGenerator_GenerateCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGenerator_GenerateCode_Call) Return(_a0 model.Code) *MockGenerator_GenerateCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenerator_GenerateCode_Call) RunAndReturn(run func() model.Code) *MockGenerator_GenerateCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
