// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/avc-dev/url-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockURLService is an autogenerated mock type for the URLService type
type MockURLService struct {
	mock.Mock
}

type MockURLService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLService) EXPECT() *MockURLService_Expecter {
	return &MockURLService_Expecter{mock: &_m.Mock}
}

// CreateShortURL provides a mock function with given fields: originalURL
func (_m *MockURLService) CreateShortURL(originalURL model.URL) (model.Code, error) {
	ret := _m.Called(originalURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 model.Code
	var r1 error
	if rf, ok := ret.Get(0).(func(model.URL) (model.Code, error)); ok {
		return rf(originalURL)
	}
	if rf, ok := ret.Get(0).(func(model.URL) model.Code); ok {
		r0 = rf(originalURL)
	} else {
		r0 = ret.Get(0).(model.Code)
	}

	if rf, ok := ret.Get(1).(func(model.URL) error); ok {
		r1 = rf(originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_CreateShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURL'
type MockURLService_CreateShortURL_Call struct {
	*mock.Call
}

// CreateShortURL is a helper method to define mock.On call
//   - originalURL model.URL
func (_e *MockURLService_Expecter) CreateShortURL(originalURL interface{}) *MockURLService_CreateShortURL_Call {
	return &MockURLService_CreateShortURL_Call{Call: _e.mock.On("CreateShortURL", originalURL)}
}

func (_c *MockURLService_CreateShortURL_Call) Run(run func(originalURL model.URL)) *MockURLService_CreateShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.URL))
	})
	return _c
}

func (_c *MockURLService_CreateShortURL_Call) Return(_a0 model.Code, _a1 error) *MockURLService_CreateShortURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_CreateShortURL_Call) RunAndReturn(run func(model.URL) (model.Code, error)) *MockURLService_CreateShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLService creates a new instance of MockURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLService {
	mock := &MockURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
