// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/avc-dev/url-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockURLRepository is an autogenerated mock type for the URLRepository type
type MockURLRepository struct {
	mock.Mock
}

type MockURLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepository) EXPECT() *MockURLRepository_Expecter {
	return &MockURLRepository_Expecter{mock: &_m.Mock}
}

// CreateURL provides a mock function with given fields: code, url
func (_m *MockURLRepository) CreateURL(code model.Code, url model.URL) error {
	ret := _m.Called(code, url)

	if len(ret) == 0 {
		panic("no return value specified for CreateURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Code, model.URL) error); ok {
		r0 = rf(code, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLRepository_CreateURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateURL'
type MockURLRepository_CreateURL_Call struct {
	*mock.Call
}

// CreateURL is a helper method to define mock.On call
//   - code model.Code
//   - url model.URL
func (_e *MockURLRepository_Expecter) CreateURL(code interface{}, url interface{}) *MockURLRepository_CreateURL_Call {
	return &MockURLRepository_CreateURL_Call{Call: _e.mock.On("CreateURL", code, url)}
}

func (_c *MockURLRepository_CreateURL_Call) Run(run func(code model.Code, url model.URL)) *MockURLRepository_CreateURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Code), args[1].(model.URL))
	})
	return _c
}

func (_c *MockURLRepository_CreateURL_Call) Return(_a0 error) *MockURLRepository_CreateURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_CreateURL_Call) RunAndReturn(run func(model.Code, model.URL) error) *MockURLRepository_CreateURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLByCode provides a mock function with given fields: code
func (_m *MockURLRepository) GetURLByCode(code model.Code) (model.URL, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetURLByCode")
	}

	var r0 model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Code) (model.URL, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(model.Code) model.URL); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(model.URL)
	}

	if rf, ok := ret.Get(1).(func(model.Code) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepository_GetURLByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLByCode'
type MockURLRepository_GetURLByCode_Call struct {
	*mock.Call
}

// GetURLByCode is a helper method to define mock.On call
//   - code model.Code
func (_e *MockURLRepository_Expecter) GetURLByCode(code interface{}) *MockURLRepository_GetURLByCode_Call {
	return &MockURLRepository_GetURLByCode_Call{Call: _e.mock.On("GetURLByCode", code)}
}

func (_c *MockURLRepository_GetURLByCode_Call) Run(run func(code model.Code)) *MockURLRepository_GetURLByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Code))
	})
	return _c
}

func (_c *MockURLRepository_GetURLByCode_Call) Return(_a0 model.URL, _a1 error) *MockURLRepository_GetURLByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepository_GetURLByCode_Call) RunAndReturn(run func(model.Code) (model.URL, error)) *MockURLRepository_GetURLByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLRepository creates a new instance of MockURLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepository {
	mock := &MockURLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
