// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/avc-dev/url-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockURLRepository is an autogenerated mock type for the URLRepository type
type MockURLRepository struct {
	mock.Mock
}

type MockURLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepository) EXPECT() *MockURLRepository_Expecter {
	return &MockURLRepository_Expecter{mock: &_m.Mock}
}

// CreateOrGetURL provides a mock function with given fields: code, url, userID
func (_m *MockURLRepository) CreateOrGetURL(code model.Code, url model.URL, userID string) (model.Code, bool, error) {
	ret := _m.Called(code, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrGetURL")
	}

	var r0 model.Code
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(model.Code, model.URL, string) (model.Code, bool, error)); ok {
		return rf(code, url, userID)
	}
	if rf, ok := ret.Get(0).(func(model.Code, model.URL, string) model.Code); ok {
		r0 = rf(code, url, userID)
	} else {
		r0 = ret.Get(0).(model.Code)
	}

	if rf, ok := ret.Get(1).(func(model.Code, model.URL, string) bool); ok {
		r1 = rf(code, url, userID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(model.Code, model.URL, string) error); ok {
		r2 = rf(code, url, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockURLRepository_CreateOrGetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrGetURL'
type MockURLRepository_CreateOrGetURL_Call struct {
	*mock.Call
}

// CreateOrGetURL is a helper method to define mock.On call
//   - code model.Code
//   - url model.URL
//   - userID string
func (_e *MockURLRepository_Expecter) CreateOrGetURL(code interface{}, url interface{}, userID interface{}) *MockURLRepository_CreateOrGetURL_Call {
	return &MockURLRepository_CreateOrGetURL_Call{Call: _e.mock.On("CreateOrGetURL", code, url, userID)}
}

func (_c *MockURLRepository_CreateOrGetURL_Call) Run(run func(code model.Code, url model.URL, userID string)) *MockURLRepository_CreateOrGetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Code), args[1].(model.URL), args[2].(string))
	})
	return _c
}

func (_c *MockURLRepository_CreateOrGetURL_Call) Return(_a0 model.Code, _a1 bool, _a2 error) *MockURLRepository_CreateOrGetURL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockURLRepository_CreateOrGetURL_Call) RunAndReturn(run func(model.Code, model.URL, string) (model.Code, bool, error)) *MockURLRepository_CreateOrGetURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateURLsBatch provides a mock function with given fields: urls, userID
func (_m *MockURLRepository) CreateURLsBatch(urls map[model.Code]model.URL, userID string) error {
	ret := _m.Called(urls, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateURLsBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[model.Code]model.URL, string) error); ok {
		r0 = rf(urls, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLRepository_CreateURLsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateURLsBatch'
type MockURLRepository_CreateURLsBatch_Call struct {
	*mock.Call
}

// CreateURLsBatch is a helper method to define mock.On call
//   - urls map[model.Code]model.URL
//   - userID string
func (_e *MockURLRepository_Expecter) CreateURLsBatch(urls interface{}, userID interface{}) *MockURLRepository_CreateURLsBatch_Call {
	return &MockURLRepository_CreateURLsBatch_Call{Call: _e.mock.On("CreateURLsBatch", urls, userID)}
}

func (_c *MockURLRepository_CreateURLsBatch_Call) Run(run func(urls map[model.Code]model.URL, userID string)) *MockURLRepository_CreateURLsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[model.Code]model.URL), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepository_CreateURLsBatch_Call) Return(_a0 error) *MockURLRepository_CreateURLsBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_CreateURLsBatch_Call) RunAndReturn(run func(map[model.Code]model.URL, string) error) *MockURLRepository_CreateURLsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteURLsBatch provides a mock function with given fields: codes, userID
func (_m *MockURLRepository) DeleteURLsBatch(codes []model.Code, userID string) error {
	ret := _m.Called(codes, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURLsBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Code, string) error); ok {
		r0 = rf(codes, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLRepository_DeleteURLsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURLsBatch'
type MockURLRepository_DeleteURLsBatch_Call struct {
	*mock.Call
}

// DeleteURLsBatch is a helper method to define mock.On call
//   - codes []model.Code
//   - userID string
func (_e *MockURLRepository_Expecter) DeleteURLsBatch(codes interface{}, userID interface{}) *MockURLRepository_DeleteURLsBatch_Call {
	return &MockURLRepository_DeleteURLsBatch_Call{Call: _e.mock.On("DeleteURLsBatch", codes, userID)}
}

func (_c *MockURLRepository_DeleteURLsBatch_Call) Run(run func(codes []model.Code, userID string)) *MockURLRepository_DeleteURLsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.Code), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepository_DeleteURLsBatch_Call) Return(_a0 error) *MockURLRepository_DeleteURLsBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_DeleteURLsBatch_Call) RunAndReturn(run func([]model.Code, string) error) *MockURLRepository_DeleteURLsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLByCode provides a mock function with given fields: code
func (_m *MockURLRepository) GetURLByCode(code model.Code) (model.URL, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetURLByCode")
	}

	var r0 model.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Code) (model.URL, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(model.Code) model.URL); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(model.URL)
	}

	if rf, ok := ret.Get(1).(func(model.Code) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepository_GetURLByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLByCode'
type MockURLRepository_GetURLByCode_Call struct {
	*mock.Call
}

// GetURLByCode is a helper method to define mock.On call
//   - code model.Code
func (_e *MockURLRepository_Expecter) GetURLByCode(code interface{}) *MockURLRepository_GetURLByCode_Call {
	return &MockURLRepository_GetURLByCode_Call{Call: _e.mock.On("GetURLByCode", code)}
}

func (_c *MockURLRepository_GetURLByCode_Call) Run(run func(code model.Code)) *MockURLRepository_GetURLByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Code))
	})
	return _c
}

func (_c *MockURLRepository_GetURLByCode_Call) Return(_a0 model.URL, _a1 error) *MockURLRepository_GetURLByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepository_GetURLByCode_Call) RunAndReturn(run func(model.Code) (model.URL, error)) *MockURLRepository_GetURLByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLsByUserID provides a mock function with given fields: userID, baseURL
func (_m *MockURLRepository) GetURLsByUserID(userID string, baseURL string) ([]model.UserURLResponse, error) {
	ret := _m.Called(userID, baseURL)

	if len(ret) == 0 {
		panic("no return value specified for GetURLsByUserID")
	}

	var r0 []model.UserURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]model.UserURLResponse, error)); ok {
		return rf(userID, baseURL)
	}
	if rf, ok := ret.Get(0).(func(string, string) []model.UserURLResponse); ok {
		r0 = rf(userID, baseURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, baseURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepository_GetURLsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLsByUserID'
type MockURLRepository_GetURLsByUserID_Call struct {
	*mock.Call
}

// GetURLsByUserID is a helper method to define mock.On call
//   - userID string
//   - baseURL string
func (_e *MockURLRepository_Expecter) GetURLsByUserID(userID interface{}, baseURL interface{}) *MockURLRepository_GetURLsByUserID_Call {
	return &MockURLRepository_GetURLsByUserID_Call{Call: _e.mock.On("GetURLsByUserID", userID, baseURL)}
}

func (_c *MockURLRepository_GetURLsByUserID_Call) Run(run func(userID string, baseURL string)) *MockURLRepository_GetURLsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepository_GetURLsByUserID_Call) Return(_a0 []model.UserURLResponse, _a1 error) *MockURLRepository_GetURLsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepository_GetURLsByUserID_Call) RunAndReturn(run func(string, string) ([]model.UserURLResponse, error)) *MockURLRepository_GetURLsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// IsCodeUnique provides a mock function with given fields: code
func (_m *MockURLRepository) IsCodeUnique(code model.Code) bool {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for IsCodeUnique")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(model.Code) bool); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockURLRepository_IsCodeUnique_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCodeUnique'
type MockURLRepository_IsCodeUnique_Call struct {
	*mock.Call
}

// IsCodeUnique is a helper method to define mock.On call
//   - code model.Code
func (_e *MockURLRepository_Expecter) IsCodeUnique(code interface{}) *MockURLRepository_IsCodeUnique_Call {
	return &MockURLRepository_IsCodeUnique_Call{Call: _e.mock.On("IsCodeUnique", code)}
}

func (_c *MockURLRepository_IsCodeUnique_Call) Run(run func(code model.Code)) *MockURLRepository_IsCodeUnique_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Code))
	})
	return _c
}

func (_c *MockURLRepository_IsCodeUnique_Call) Return(_a0 bool) *MockURLRepository_IsCodeUnique_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_IsCodeUnique_Call) RunAndReturn(run func(model.Code) bool) *MockURLRepository_IsCodeUnique_Call {
	_c.Call.Return(run)
	return _c
}

// IsURLOwnedByUser provides a mock function with given fields: code, userID
func (_m *MockURLRepository) IsURLOwnedByUser(code model.Code, userID string) bool {
	ret := _m.Called(code, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsURLOwnedByUser")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(model.Code, string) bool); ok {
		r0 = rf(code, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockURLRepository_IsURLOwnedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsURLOwnedByUser'
type MockURLRepository_IsURLOwnedByUser_Call struct {
	*mock.Call
}

// IsURLOwnedByUser is a helper method to define mock.On call
//   - code model.Code
//   - userID string
func (_e *MockURLRepository_Expecter) IsURLOwnedByUser(code interface{}, userID interface{}) *MockURLRepository_IsURLOwnedByUser_Call {
	return &MockURLRepository_IsURLOwnedByUser_Call{Call: _e.mock.On("IsURLOwnedByUser", code, userID)}
}

func (_c *MockURLRepository_IsURLOwnedByUser_Call) Run(run func(code model.Code, userID string)) *MockURLRepository_IsURLOwnedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Code), args[1].(string))
	})
	return _c
}

func (_c *MockURLRepository_IsURLOwnedByUser_Call) Return(_a0 bool) *MockURLRepository_IsURLOwnedByUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_IsURLOwnedByUser_Call) RunAndReturn(run func(model.Code, string) bool) *MockURLRepository_IsURLOwnedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLRepository creates a new instance of MockURLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepository {
	mock := &MockURLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
