// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/avc-dev/url-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockURLUsecase is an autogenerated mock type for the URLUsecase type
type MockURLUsecase struct {
	mock.Mock
}

type MockURLUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLUsecase) EXPECT() *MockURLUsecase_Expecter {
	return &MockURLUsecase_Expecter{mock: &_m.Mock}
}

// CreateShortURLFromString provides a mock function with given fields: urlString, userID
func (_m *MockURLUsecase) CreateShortURLFromString(urlString string, userID string) (string, error) {
	ret := _m.Called(urlString, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURLFromString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(urlString, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(urlString, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(urlString, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLUsecase_CreateShortURLFromString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURLFromString'
type MockURLUsecase_CreateShortURLFromString_Call struct {
	*mock.Call
}

// CreateShortURLFromString is a helper method to define mock.On call
//   - urlString string
//   - userID string
func (_e *MockURLUsecase_Expecter) CreateShortURLFromString(urlString interface{}, userID interface{}) *MockURLUsecase_CreateShortURLFromString_Call {
	return &MockURLUsecase_CreateShortURLFromString_Call{Call: _e.mock.On("CreateShortURLFromString", urlString, userID)}
}

func (_c *MockURLUsecase_CreateShortURLFromString_Call) Run(run func(urlString string, userID string)) *MockURLUsecase_CreateShortURLFromString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockURLUsecase_CreateShortURLFromString_Call) Return(_a0 string, _a1 error) *MockURLUsecase_CreateShortURLFromString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLUsecase_CreateShortURLFromString_Call) RunAndReturn(run func(string, string) (string, error)) *MockURLUsecase_CreateShortURLFromString_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShortURLsBatch provides a mock function with given fields: urlStrings, userID
func (_m *MockURLUsecase) CreateShortURLsBatch(urlStrings []string, userID string) ([]string, error) {
	ret := _m.Called(urlStrings, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURLsBatch")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, string) ([]string, error)); ok {
		return rf(urlStrings, userID)
	}
	if rf, ok := ret.Get(0).(func([]string, string) []string); ok {
		r0 = rf(urlStrings, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = rf(urlStrings, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLUsecase_CreateShortURLsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURLsBatch'
type MockURLUsecase_CreateShortURLsBatch_Call struct {
	*mock.Call
}

// CreateShortURLsBatch is a helper method to define mock.On call
//   - urlStrings []string
//   - userID string
func (_e *MockURLUsecase_Expecter) CreateShortURLsBatch(urlStrings interface{}, userID interface{}) *MockURLUsecase_CreateShortURLsBatch_Call {
	return &MockURLUsecase_CreateShortURLsBatch_Call{Call: _e.mock.On("CreateShortURLsBatch", urlStrings, userID)}
}

func (_c *MockURLUsecase_CreateShortURLsBatch_Call) Run(run func(urlStrings []string, userID string)) *MockURLUsecase_CreateShortURLsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].(string))
	})
	return _c
}

func (_c *MockURLUsecase_CreateShortURLsBatch_Call) Return(_a0 []string, _a1 error) *MockURLUsecase_CreateShortURLsBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLUsecase_CreateShortURLsBatch_Call) RunAndReturn(run func([]string, string) ([]string, error)) *MockURLUsecase_CreateShortURLsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function with given fields: code
func (_m *MockURLUsecase) GetOriginalURL(code string) (string, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLUsecase_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type MockURLUsecase_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - code string
func (_e *MockURLUsecase_Expecter) GetOriginalURL(code interface{}) *MockURLUsecase_GetOriginalURL_Call {
	return &MockURLUsecase_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", code)}
}

func (_c *MockURLUsecase_GetOriginalURL_Call) Run(run func(code string)) *MockURLUsecase_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLUsecase_GetOriginalURL_Call) Return(_a0 string, _a1 error) *MockURLUsecase_GetOriginalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLUsecase_GetOriginalURL_Call) RunAndReturn(run func(string) (string, error)) *MockURLUsecase_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLsByUserID provides a mock function with given fields: userID
func (_m *MockURLUsecase) GetURLsByUserID(userID string) ([]model.UserURLResponse, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetURLsByUserID")
	}

	var r0 []model.UserURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]model.UserURLResponse, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []model.UserURLResponse); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLUsecase_GetURLsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLsByUserID'
type MockURLUsecase_GetURLsByUserID_Call struct {
	*mock.Call
}

// GetURLsByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockURLUsecase_Expecter) GetURLsByUserID(userID interface{}) *MockURLUsecase_GetURLsByUserID_Call {
	return &MockURLUsecase_GetURLsByUserID_Call{Call: _e.mock.On("GetURLsByUserID", userID)}
}

func (_c *MockURLUsecase_GetURLsByUserID_Call) Run(run func(userID string)) *MockURLUsecase_GetURLsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLUsecase_GetURLsByUserID_Call) Return(_a0 []model.UserURLResponse, _a1 error) *MockURLUsecase_GetURLsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLUsecase_GetURLsByUserID_Call) RunAndReturn(run func(string) ([]model.UserURLResponse, error)) *MockURLUsecase_GetURLsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLUsecase creates a new instance of MockURLUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLUsecase {
	mock := &MockURLUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
