// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/avc-dev/url-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCodeChecker is an autogenerated mock type for the CodeChecker type
type MockCodeChecker struct {
	mock.Mock
}

type MockCodeChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodeChecker) EXPECT() *MockCodeChecker_Expecter {
	return &MockCodeChecker_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: code
func (_m *MockCodeChecker) Exists(code model.Code) (bool, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Code) (bool, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(model.Code) bool); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(model.Code) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCodeChecker_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCodeChecker_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - code model.Code
func (_e *MockCodeChecker_Expecter) Exists(code interface{}) *MockCodeChecker_Exists_Call {
	return &MockCodeChecker_Exists_Call{Call: _e.mock.On("Exists", code)}
}

func (_c *MockCodeChecker_Exists_Call) Run(run func(code model.Code)) *MockCodeChecker_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Code))
	})
	return _c
}

func (_c *MockCodeChecker_Exists_Call) Return(_a0 bool, _a1 error) *MockCodeChecker_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCodeChecker_Exists_Call) RunAndReturn(run func(model.Code) (bool, error)) *MockCodeChecker_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCodeChecker creates a new instance of MockCodeChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodeChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodeChecker {
	mock := &MockCodeChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
