// Package pool provides a generic, type-safe wrapper around sync.Pool
// for objects that implement the Reset() method.
package pool

import "sync"

// Resettable is a constraint for types that expose a Reset() method.
// It is satisfied by pointer types whose Reset() was generated by the reset generator.
type Resettable interface {
	Reset()
}

// Pool is a generic wrapper around sync.Pool that stores objects of type T.
// T must satisfy the Resettable constraint, i.e. have a Reset() method.
// In practice T is a pointer type (e.g. *MyStruct) because Reset() is
// generated with a pointer receiver.
type Pool[T Resettable] struct {
	p sync.Pool
}

// New creates and returns a pointer to a new Pool[T].
// factory is called by the underlying sync.Pool whenever Get is invoked
// and the pool is empty; it must return a freshly allocated T.
func New[T Resettable](factory func() T) *Pool[T] {
	return &Pool[T]{
		p: sync.Pool{
			New: func() any {
				return factory()
			},
		},
	}
}

// Get retrieves an object from the pool.
// If the pool is empty, the factory function supplied to New is called.
func (p *Pool[T]) Get() T {
	return p.p.Get().(T)
}

// Put resets v and returns it to the pool for reuse.
// Reset() is called before the object is placed back so that the next
// caller always receives a clean, zero-valued object.
func (p *Pool[T]) Put(v T) {
	v.Reset()
	p.p.Put(v)
}
