// Package main implements a code generator that produces Reset() methods
// for structs annotated with the "// generate:reset" comment.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root := "."

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		base := d.Name()
		if base != "." && (strings.HasPrefix(base, ".") || base == "vendor" || base == "testdata") {
			return filepath.SkipDir
		}
		processDir(path)
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "walk error: %v\n", err)
		os.Exit(1)
	}
}

// structInfo holds the name and fields of a struct that needs a Reset() method.
type structInfo struct {
	Name   string
	Fields []fieldInfo
}

type fieldInfo struct {
	Name string
	Type ast.Expr
}

// processDir scans a directory for Go packages, finds structs annotated with
// "// generate:reset", and writes reset.gen.go with their Reset() methods.
func processDir(dir string) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		name := fi.Name()
		return !strings.HasSuffix(name, "_test.go") && name != "reset.gen.go"
	}, parser.ParseComments)
	if err != nil || len(pkgs) == 0 {
		return
	}

	for pkgName, pkg := range pkgs {
		structs := collectStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		var buf bytes.Buffer
		writeFile(&buf, pkgName, structs)

		src, err := format.Source(buf.Bytes())
		if err != nil {
			fmt.Fprintf(os.Stderr, "format error in %s: %v\n--- raw output ---\n%s\n", dir, err, buf.Bytes())
			continue
		}

		outPath := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(outPath, src, 0644); err != nil {
			fmt.Fprintf(os.Stderr, "write error %s: %v\n", outPath, err)
		} else {
			fmt.Printf("generated %s\n", outPath)
		}
	}
}

// collectStructs returns all structs in the package that have the // generate:reset annotation.
func collectStructs(pkg *ast.Package) []structInfo {
	var structs []structInfo
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			if !hasResetAnnotation(genDecl) {
				continue
			}
			for _, spec := range genDecl.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				si := structInfo{Name: ts.Name.Name}
				for _, field := range st.Fields.List {
					// Skip embedded (anonymous) fields.
					if len(field.Names) == 0 {
						continue
					}
					for _, name := range field.Names {
						si.Fields = append(si.Fields, fieldInfo{
							Name: name.Name,
							Type: field.Type,
						})
					}
				}
				structs = append(structs, si)
			}
		}
	}
	return structs
}

// hasResetAnnotation checks whether the GenDecl's doc comment contains "// generate:reset".
func hasResetAnnotation(decl *ast.GenDecl) bool {
	if decl.Doc == nil {
		return false
	}
	for _, c := range decl.Doc.List {
		if c.Text == "// generate:reset" {
			return true
		}
	}
	return false
}

// writeFile writes the complete generated source file to buf.
func writeFile(buf *bytes.Buffer, pkg string, structs []structInfo) {
	buf.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(buf, "package %s\n\n", pkg)
	for _, s := range structs {
		writeResetMethod(buf, s)
	}
}

// writeResetMethod writes a single Reset() method for the given struct.
func writeResetMethod(buf *bytes.Buffer, s structInfo) {
	recv := strings.ToLower(string(s.Name[0]))
	fmt.Fprintf(buf, "func (%s *%s) Reset() {\n", recv, s.Name)
	fmt.Fprintf(buf, "\tif %s == nil {\n\t\treturn\n\t}\n", recv)
	if len(s.Fields) > 0 {
		buf.WriteByte('\n')
	}
	for _, f := range s.Fields {
		writeFieldReset(buf, recv+"."+f.Name, f.Type, "\t")
	}
	buf.WriteString("}\n\n")
}

// writeFieldReset generates the reset statement for a single field.
func writeFieldReset(buf *bytes.Buffer, expr string, typ ast.Expr, indent string) {
	switch t := typ.(type) {
	case *ast.Ident:
		if zv, ok := zeroLiteral(t.Name); ok {
			// Primitive type — assign zero literal.
			fmt.Fprintf(buf, "%s%s = %s\n", indent, expr, zv)
		} else {
			// Named type (struct, typedef, etc.) — try Reset() via type assertion.
			fmt.Fprintf(buf, "%sif resetter, ok := any(&%s).(interface{ Reset() }); ok {\n", indent, expr)
			fmt.Fprintf(buf, "%s\tresetter.Reset()\n", indent)
			fmt.Fprintf(buf, "%s}\n", indent)
		}

	case *ast.StarExpr:
		writePointerReset(buf, expr, t.X, indent)

	case *ast.ArrayType:
		if t.Len == nil {
			// Slice — truncate to zero length, preserving backing array.
			fmt.Fprintf(buf, "%s%s = %s[:0]\n", indent, expr, expr)
		} else {
			// Fixed-size array — assign zero value composite literal.
			fmt.Fprintf(buf, "%s%s = %s{}\n", indent, expr, exprString(typ))
		}

	case *ast.MapType:
		// Map — clear all entries.
		fmt.Fprintf(buf, "%sclear(%s)\n", indent, expr)

	case *ast.SelectorExpr:
		// Qualified type from another package — try Reset() via type assertion.
		fmt.Fprintf(buf, "%sif resetter, ok := any(&%s).(interface{ Reset() }); ok {\n", indent, expr)
		fmt.Fprintf(buf, "%s\tresetter.Reset()\n", indent)
		fmt.Fprintf(buf, "%s}\n", indent)

	case *ast.InterfaceType, *ast.FuncType, *ast.ChanType:
		// Reference types with no meaningful zero-reset — set to nil.
		fmt.Fprintf(buf, "%s%s = nil\n", indent, expr)
	}
}

// writePointerReset generates the reset logic for a pointer field.
// It dereferences the pointer and resets the underlying value if non-nil.
func writePointerReset(buf *bytes.Buffer, expr string, pointedTo ast.Expr, indent string) {
	fmt.Fprintf(buf, "%sif %s != nil {\n", indent, expr)
	inner := indent + "\t"

	switch t := pointedTo.(type) {
	case *ast.Ident:
		if zv, ok := zeroLiteral(t.Name); ok {
			// Pointer to primitive — dereference and zero.
			fmt.Fprintf(buf, "%s*%s = %s\n", inner, expr, zv)
		} else {
			// Pointer to struct/named type — try Reset() (pointer already satisfies interface).
			fmt.Fprintf(buf, "%sif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", inner, expr)
			fmt.Fprintf(buf, "%s\tresetter.Reset()\n", inner)
			fmt.Fprintf(buf, "%s}\n", inner)
		}

	case *ast.ArrayType:
		if t.Len == nil {
			// Pointer to slice — truncate underlying slice.
			fmt.Fprintf(buf, "%s*%s = (*%s)[:0]\n", inner, expr, expr)
		} else {
			fmt.Fprintf(buf, "%s*%s = %s{}\n", inner, expr, exprString(pointedTo))
		}

	case *ast.MapType:
		fmt.Fprintf(buf, "%sclear(*%s)\n", inner, expr)

	case *ast.SelectorExpr:
		// Pointer to external package type — try Reset().
		fmt.Fprintf(buf, "%sif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", inner, expr)
		fmt.Fprintf(buf, "%s\tresetter.Reset()\n", inner)
		fmt.Fprintf(buf, "%s}\n", inner)

	default:
		fmt.Fprintf(buf, "%sif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", inner, expr)
		fmt.Fprintf(buf, "%s\tresetter.Reset()\n", inner)
		fmt.Fprintf(buf, "%s}\n", inner)
	}

	fmt.Fprintf(buf, "%s}\n", indent)
}

// zeroLiteral returns the Go zero literal for a primitive type name.
func zeroLiteral(name string) (string, bool) {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return "0", true
	case "string":
		return `""`, true
	case "bool":
		return "false", true
	}
	return "", false
}

// exprString converts an AST type expression back to its Go source string.
// Used to produce type literals for composite zero values (e.g., [4]byte{}).
func exprString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + exprString(t.Elt)
		}
		return fmt.Sprintf("[%s]%s", exprString(t.Len), exprString(t.Elt))
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", exprString(t.Key), exprString(t.Value))
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.BasicLit:
		return t.Value
	case *ast.InterfaceType:
		return "any"
	case *ast.ChanType:
		switch t.Dir {
		case ast.SEND:
			return "chan<- " + exprString(t.Value)
		case ast.RECV:
			return "<-chan " + exprString(t.Value)
		default:
			return "chan " + exprString(t.Value)
		}
	default:
		return "interface{}"
	}
}
